package com.bookstore.entity;
// Generated Aug 2, 2022, 12:56:09 AM by Hibernate Tools 5.6.3.Final

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {

  private Integer orderId;
  private Integer bookId;
  private int quantity;
  private float subtotal;

  public OrderDetailId() {}

  public OrderDetailId(int quantity, float subtotal) {
    this.quantity = quantity;
    this.subtotal = subtotal;
  }

  public OrderDetailId(Integer orderId, Integer bookId, int quantity, float subtotal) {
    this.orderId = orderId;
    this.bookId = bookId;
    this.quantity = quantity;
    this.subtotal = subtotal;
  }

  public Integer getOrderId() {
    return this.orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public Integer getBookId() {
    return this.bookId;
  }

  public void setBookId(Integer bookId) {
    this.bookId = bookId;
  }

  public int getQuantity() {
    return this.quantity;
  }

  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }

  public float getSubtotal() {
    return this.subtotal;
  }

  public void setSubtotal(float subtotal) {
    this.subtotal = subtotal;
  }
}
